### ISSUE TITLE
Is this fsater than the uuid library? Benchmarks?

### ISSUE THREAD

**Issue by saurabhnanda** [solidsnack/system-uuid#4]
Is this faster than https://hackage.haskell.org/package/uuid-1.3.13 ? Are there any benchmarks to validate this?

**Comment by solidsnack** [comment]
It is not intended to be fast. It uses the system UUID generator. For V1 UUIDs, this means the same counter is used as any other process on the system.

Since it does a system call for each UUID, it might be slower than the other library you linked to.

The real use case for this library is a situation where the (somewhat edge of the wedge) guarantees of the system UUID generator are significant, either due to requirements or the nature of how you're explaining guarantees to users of your software.

**Comment by saurabhnanda** [comment]
Thanks for replying @solidsnack. I ran some benchmarks and found this library to be slower for my use-case, so I'm going with the `uuid` library for now.
